# Generated by Django 4.1.2 on 2022-10-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=10)),
                ('user_password', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
